name: demo_generator
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build:
  source_gen:
  demo:
    path: ../demo

dev_dependencies:
  build_test:
  build_runner:
